name: 认领新任务
description: 认领一个新的开源实习生主题任务
title: "[认领]: "
labels: ["task"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        你可以在仓库主页浏览到所有任务，也可以在 issue 列表检索已被认领的任务。
        
        请遵循此模板的填写指引来认领一个新的开源实习生任务。
        
        开始之前，请将任务的标题填写在此 issue 的标题部分。
  - type: textarea
    id: task-description
    attributes:
      label: 任务描述
      description: 请复制粘贴任务的描述部分。
      placeholder: |
        请复制粘贴任务的描述部分。
    validations:
      required: true
  - type: textarea
    id: task-requirement
    attributes:
      label: 验收标准
      description: 请复制粘贴任务的验收标准部分。在成功认领后，你将需要根据实际完成进度来更新此部分的内容。
      placeholder: |
        请复制粘贴任务的验收标准部分。
    validations:
      required: true
  - type: textarea
    id: task-contact
    attributes:
      label: 联系方式
      description: |
        请提供认领人的交流/联系方式，可以是 GitHub 帐号、邮箱、Matrix ID 等可公开的联系方式。
        如果此任务为单人（即您自己）认领，可不提供 GitHub 帐号（视为创建人认领）。
        另外，为便于交流，请在官方聊天渠道中备注自己的 GitHub 帐号。
      placeholder: |
        填写认领人员的联系方式
    validations:
      required: true
